name: More repository Deploy

on:
  push:
    branches:
      - master

jobs:
  build_site:
    runs-on: ubuntu-22.04

    name: Deploy "More" repository
    steps:
    - uses: actions/checkout@v3

    - name: Deploy More repository
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: www531.your-server.de
        protocol: ftps
        username: ${{ secrets.GHA_HETZNER_MORE_FTP_USER }}
        password: ${{ secrets.GHA_HETZNER_MORE_FTP_PASS }}
        local-dir: ./
        server-dir: /
        exclude: |
          **/staging/**
          **/.*
          **/.*/**
